### ISSUE TITLE
Incorrect balance: after import wallet.dat on Blackcoin-Lore from QT-wallet

### ISSUE THREAD

**Issue by jschaeke** [janko33bd/bitcoin#1]
After importing the old wallet.dat from a former QT wallet, the balance never reflected the actual balance; always too low. In the end 500 BLK less on 15.000 when all synced up.

**Comment by janko33bd** [comment]
If you create an empty wallet in Lore
Using "dumpwallet" command from former QT wallet and "importwallet" in Lore 
results in same balance as formr Qt wallet

**Comment by jschaeke** [comment]
Confirmed, balance is correct now.
