### ISSUE TITLE
Lore/ Qt comparison (IsProtocolV2)

### ISSUE THREAD

**Issue by BlackFoxController** [janko33bd/bitcoin#3]
Lore:
bool IsProtocolV2(int64_t nTime) const { return nTime > nProtocolV2Time && nTime != 1407053678; }

Qt (1.2.4)
inline bool IsProtocolV2(int nHeight) { return TestNet() || nHeight > 319000; }

Could any issues arise from Qt using a block height and Lore using a timestamp? 

Also notice that GetTargetSpacing is not used. Might save a few lines of code .. xD

**Comment by BlackFoxController** [comment]
Nevermind. I suppose the timestamp is encoded in the block and it's fairly straighforward check :)

**Comment by janko33bd** [comment]
close the issue ;P
