### ISSUE TITLE
Calculating the block hash

### ISSUE THREAD

**Issue by BlackFoxController** [janko33bd/bitcoin#4]
Is there a different way the block hash is calculated in comparison to bitcoin? 

I am unable to reproduce a block hash as follows:

VERSION: 1
PREVBLOCKHASH: 8d08e05ef7bae0540d5dd062980f20ca603490163816166be7ea086c57cfd8aa
MERKLE ROOT: f6d8686908b0e3604c6a012bdd9d9012b2f72d40393e006937d797ccbdfcd68d
TIME: 1464532864
BITS: 437166402
NONCE: 0

I create the HEX of that:
01000000aad8cf576c08eae76b16163816903460ca200f9862d05d0d54e0baf75ee0088d8dd6fcbdcc97d73769003e39402df7b212909ddd2b016a4c60e3b0086968d8f680ff4a5742a10e1a00000000

Convert it to binary, hash sha 256 it, convert that to binary and hash that one more time. Then flip the order. I should end up with the block hash, which is:
7260aaefbe4254d84b2d95f344256d96841d5327f40637c1802479081beec9a1

But instead of that, I get the hash: 11a34eebd7dc903e5bab649b5eefe509b7051e8975c1c65fed8d7294f3b341bd

I'm quite confused. What am I doing wrong? Am I missing a variable in the header?

For reference, this should "recreate" block 1179759:
https://chainz.cryptoid.info/blk/block.dws?1179759.htm

**Comment by janko33bd** [comment]
It should be the same

**Comment by BlackFoxController** [comment]
Yes I thought so, reading the code- but somehow I end up with a different hash, I don't understand

**Comment by janko33bd** [comment]
For the future please open issues which have something to do with the project!
Please close the issue. Thanks you.

You got answered on reddit.
https://nm.reddit.com/r/blackcoin/comments/6k0an6/verifying_a_block_hash/djrf84i/

**Comment by BlackFoxController** [comment]
I used the wrong version. Thanks ok
